messages:
  no-permission: "&c&lYou do not have permission to do this!"
  player-not-found: "&c&lPlayer not found."
  reloaded: "&aSuccessfully reloaded config."
  saved: "&aYour inventory has been saved."
  restored: "&aYour previous saved inventory has been restored."
  no-inventory-restore: "&cYou do not have an inventory to restore in this world."
  inventory-saved-death: "&aYou have died, but your inventory has been saved. Restore it using &2/restoreinventory&a."
  inventory-saved-world-change: "&aYou have changed worlds and your inventory has been saved. Restore it using &2/restoreinventory&a."
  inventory-restored-world-change: "&aYou have changed worlds and your inventory has been restored."
  invalid-storage-id: "&cStorage ID must be from 1 to 9."
  storage-cleared: "&aSuccessfully cleared your storage."

clear-on-save: true # Permission: saveinventory.save.clear
save-on-death: true # Permission: saveinventory.save.death
save-on-world-change: true # Permission: saveinventory.save.worldchange
# If true, the command /restoreinventory will not wipe previous saved data.
# You will be able to use the command multiple times to restore previous saved inventory.
keep-last-saved-inventory: false

# If 'per-world-save' is enabled, then the inventory will be saved for each world.
# Ex. if player saves his inventory in world 'X', then he won't be able to restore it in world 'Y'.
per-world-save: false

# If 'per-world-save' is enabled, the automatic restore/save
# on join will work for the new world, leave for previous world.

# Will trigger automatic inventory restore when entering one of the worlds listed below.
auto-save-on-world-join:
  - world

# Will trigger automatic inventory restore when entering one of the worlds listed below.
auto-restore-on-world-join: []

# Will trigger automatic inventory save when leaving one of the worlds listed below.
auto-save-on-world-leave: []

# Will trigger automatic inventory restore when leaving one of the worlds listed below.
auto-restore-on-world-leave: []