main: me.m0dii.saveinventory.SaveInventory
name: SaveInventory
author: M0dii
version: ${version}
api-version: 1.16
commands:
  saveinventory:
    permission: extraenchants.command.save
    description: Save inventory command.
    aliases: [saveinv]
  restoreinventory:
    permission: extraenchants.command.restore
    description: Restore inventory comamnd.
    aliases: [restoreinv]